import sekre1 from "../../../public/organogram/fotopanitia/fotodummy.jpeg";
import type { OrganogramData } from "~/types/organogram";

export const cardDataSekretaris : OrganogramData[] = [
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Talitha Giovani A.N.",
        title: "SEKRETARIS 1",
        batch: "TG'22",
        division: "Sekretaris",
        // ditambah bidang
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Kayla Annisa S.",
        title: "SEKRETARIS 2",
        batch: "GD'22",
        division: "Sekretaris",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Najwa Maharani",
        title: "BENDAHARA 1",
        batch: "GD'22",
        division: "Bendahara",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Putri Alinur W.",
        title: "BENDAHARA 2",
        batch: "KI'22",
        division: "Bendahara",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Nasha Aliya",
        title: "KETUA DIVISI",
        batch: "MA'23",
        division: "Perizinan",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Qanitah Hafizhah",
        title: "WAKIL KETUA DIVISI",
        batch: "TL'23",
        division: "Perizinan",
    },
]

export const cardDataManajemenPersonalia : OrganogramData[] = [
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Julian Putra S.",
        title: "KETUA DIVISI",
        batch: "TG'22",
        division: "PSDM",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Shofie Aliya M.",
        title: "WAKIL KETUA DIVISI",
        batch: "TG'22",
        division: "PSDM",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Marcel Jason Y.",
        title: "KETUA DIVISI",
        batch: "MS'22",
        division: "MSDM",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Dharfin yashi S.",
        title: "WAKIL KETUA DIVISI",
        batch: "MT'22",
        division: "MSDM",
    },
];

export const cardDataAcara : OrganogramData[] = [
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Nora Aurora P.",
        title: "KETUA DIVISI",
        batch: "TK'22",
        division: "Appreciation",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Sayidatina Syarifa",
        title: "WAKIL KETUA DIVISI",
        batch: "TK'22",
        division: "Appreciation",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Rayhan Arif P.",
        title: "KETUA DIVISI",
        batch: "MT'22",
        division: "Education",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Marcelino Gabriel S.",
        title: "WAKIL KETUA DIVISI",
        batch: "AE'22",
        division: "Education",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Mikhael Xylen S.",
        title: "KETUA DIVISI",
        batch: "PG'23",
        division: "Entertainment",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Sydney Kurniawan",
        title: "WAKIL KETUA DIVISI",
        batch: "MA'23",
        division: "Entetainment",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Muhammad Ikbal A.",
        title: "KETUA DIVISI",
        batch: "BA'22",
        division: "Multikampus",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Radhiya Rifayani",
        title: "WAKIL KETUA DIVISI",
        batch: "DE'23",
        division: "Multikampus",
    },
];

export const cardDataLapangan : OrganogramData[] = [
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Elicia Hardiyanti",
        title: "SEKRETARIS LAPANGAN 1",
        batch: "GD'22",
        division: "Lapangan",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Sabrina Fitra S.",
        title: "SEKRETARIS LAPANGAN 2",
        batch: "KL'23",
        division: "Lapangan",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Mikael Amadeus T.",
        title: "KOMANDAN LAPANGAN",
        batch: "MS'22",
        division: "Zona Basecamp",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Zahwa Endah H.",
        title: "KOMANDAN PASUKAN",
        batch: "IL'23",
        division: "Zona Basecamp",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Rachel Elisabeth",
        title: "KOMANDAN LAPANGAN",
        batch: "AE'22",
        division: "Zona Saraga",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Stanislaus Ardy B.",
        title: "KOMANDAN PASUKAN",
        batch: "II'23",
        division: "Zona Saraga",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Ira Nazwa F.",
        title: "KOMANDAN LAPANGAN",
        batch: "GD'22",
        division: "Zona Tunnel",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Miftah Fauzaan M.",
        title: "KOMANDAN PASUKAN",
        batch: "EL'23",
        division: "Zona Tunnel",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Johanes Baptista A.",
        title: "KOMANDAN LAPANGAN",
        batch: "GL'22",
        division: "Zona Mobilisasi",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Muhammad Dhafin A.",
        title: "KOMANDAN PASUKAN",
        batch: "AE'23",
        division: "Zona Mobilisasi",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Rayyan Nusaly",
        title: "KOMANDAN LAPANGAN",
        batch: "MS'22",
        division: "Zona Performance",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Raykal Abdullah S.",
        title: "KOMANDAN PASUKAN",
        batch: "GD'23",
        division: "Zona Performance",
    },
];

export const cardDataFundraising : OrganogramData[] = [
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Harits Imtiyaaz T.",
        title: "KETUA DIVISI",
        batch: "MB'23",
        division: "Entrepreneurship",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Florentina Tiffani S.",
        title: "WAKIL KETUA DIVISI",
        batch: "AK'23",
        division: "Entrepreneurship",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Zefanya Valentino B.",
        title: "KETUA DIVISI",
        batch: "MB'23",
        division: "Sponsorship",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Daffa Mochamad S.",
        title: "WAKIL KETUA DIVISI",
        batch: "MB'23",
        division: "Sponsorship",
    },
];

export const cardDataKreatif : OrganogramData[] = [
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Reyvia Shafa M.",
        title: "KETUA DIVISI",
        batch: "DKV'22",
        division: "PubDok",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Maulidya Farras D.",
        title: "WAKIL KETUA DIVISI",
        batch: "IL'23",
        division: "PubDok",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Amargia S.",
        title: "KETUA DIVISI",
        batch: "KR'22",
        division: "Grafis",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Ibtisam Sabrina B.",
        title: "WAKIL KETUA DIVISI",
        batch: "DKV'22",
        division: "Grafis",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Nafisa Ardelia Y.",
        title: "KETUA DIVISI",
        batch: "DI'23",
        division: "Medinfo",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Said Mundji",
        title: "WAKIL KETUA DIVISI",
        batch: "DP'23",
        division: "Medinfo",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Feodore Louise S.",
        title: "KETUA DIVISI",
        batch: "SR'23",
        division: "Musik",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Galih Muhammad S.",
        title: "WAKIL KETUA DIVISI",
        batch: "EL'23",
        division: "Musik",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Khansa Fawnia",
        title: "KETUA DIVISI",
        batch: "KR'23",
        division: "Artistik",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Dashley Helena C.",
        title: "WAKIL KETUA DIVISI",
        batch: "DP'23",
        division: "Artistik",
    },
];

export const cardDataRelasi : OrganogramData[] = [
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Muhammad Alif",
        title: "KETUA DIVISI",
        batch: "SA'22",
        division: "Intrakampus",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Nisrina Syadza",
        title: "WAKIL KETUA DIVISI",
        batch: "PL'23",
        division: "Intrakampus",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Nayla Najwa K.",
        title: "KETUA DIVISI",
        batch: "BA'23",
        division: "Ekstrakampus",
    },
    {
        frameType: "dark",
        photo: sekre1.src,
        name: "Salwa Azzahra P.",
        title: "WAKIL KETUA DIVISI",
        batch: "TI'22",
        division: "Ekstrakampus",
    },
];

export const cardDataOperasional : OrganogramData[] = [
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Nurrizki Fathami",
        title: "KETUA DIVISI",
        batch: "ME'22",
        division: "Logistik",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Sulthan N. R.",
        title: "WAKIL KETUA DIVISI",
        batch: "TF'22",
        division: "Logistik",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Muhammad Iyyas S.",
        title: "KETUA DIVISI",
        batch: "AE'22",
        division: "Produksi",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Sultan Favian",
        title: "WAKIL KETUA DIVISI",
        batch: "AE'22",
        division: "Produksi",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "Adi Haditya N.",
        title: "KETUA DIVISI",
        batch: "MS'22",
        division: "IT",
    },
    {
        frameType: "light",
        photo: sekre1.src,
        name: "M. Dicky Isra",
        title: "WAKIL KETUA DIVISI",
        batch: "IF'23",
        division: "IT",
    },
];
